### ISSUE TITLE
Build on wercker failing, because of an old API call.

### ISSUE THREAD

**Issue by napcae** [zedtux/brewformulas.org#35]
~~The build will always fail, because the call to https://coveralls.io/api/v1 fails, since it throws a HTTP 404.~~

```
[Coveralls] Submitting to https://coveralls.io/api/v1
Coveralls encountered an exception:
RestClient::UnprocessableEntity
422 Unprocessable Entity
/pipeline/cache/bundle-install/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
/pipeline/cache/bundle-install/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
/pipeline/cache/bundle-install/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
/pipeline/cache/bundle-install/ruby/2.2.0/gems/webmock-1.21.0/lib/webmock/http_lib_adapters/net_http.rb:123:in `start_without_connect'
/pipeline/cache/bundle-install/ruby/2.2.0/gems/webmock-1.21.0/lib/webmock/http_lib_adapters/net_http.rb:150:in `start'
/pipeline/cache/bundle-install/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
/pipeline/cache/bundle-install/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
/pipeline/cache/bundle-install/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
/pipeline/cache/bundle-install/ruby/2.2.0/gems/coveralls-0.8.1/lib/coveralls/api.rb:23:in `post_json'
/pipeline/cache/bundle-install/ruby/2.2.0/gems/coveralls-0.8.1/lib/coveralls/simplecov.rb:72:in `format'
/pipeline/cache/bundle-install/ruby/2.2.0/gems/simplecov-0.10.0/lib/simplecov/formatter/multi_formatter.rb:15:in `block in format'
/pipeline/cache/bundle-install/ruby/2.2.0/gems/simplecov-0.10.0/lib/simplecov/formatter/multi_formatter.rb:13:in `map'
/pipeline/cache/bundle-install/ruby/2.2.0/gems/simplecov-0.10.0/lib/simplecov/formatter/multi_formatter.rb:13:in `format'
/pipeline/cache/bundle-install/ruby/2.2.0/gems/simplecov-0.10.0/lib/simplecov/result.rb:46:in `format!'
/pipeline/cache/bundle-install/ruby/2.2.0/gems/simplecov-0.10.0/lib/simplecov/configuration.rb:159:in `block in at_exit'
/pipeline/cache/bundle-install/ruby/2.2.0/gems/simplecov-0.10.0/lib/simplecov/defaults.rb:60:in `call'
/pipeline/cache/bundle-install/ruby/2.2.0/gems/simplecov-0.10.0/lib/simplecov/defaults.rb:60:in `block in <top (required)>'
{"message":"Couldn't find a repository matching this job.","error":true}
```

~~I suggest removing coveralls, or updating the settings.~~

Update1:
Probably has something todo with rest client and malformed data(?) I'm looking into this.

Update2:
Is [this](http://stackoverflow.com/a/19168135/879648) the solution for ```/app/controllers/application_controller.rb```?

**Comment by zedtux** [comment]
Hello @napcae,

First of all, thank you for your interest in my project :-)

Secondly, you pointed an interesting SO answer, but your commit is doing something different.
In my opinion, the `protect_from_forgery with: :null_session` should be used, but only in case it's an API call, not for the rest of the website.
